version: 1
name: "Total Readings"
slug: "kpi-reading-count"
spaceSlug: "airlab"
tableName: "airlab_readings"
updatedAt: "2026-02-15T00:00:00.000Z"

metricQuery:
  exploreName: "airlab_readings"
  dimensions: []
  metrics:
    - "airlab_readings_reading_count"
  filters: {}
  sorts: []
  limit: 1
  tableCalculations: []

chartConfig:
  type: "big_number"
  config:
    selectedField: "airlab_readings_reading_count"
    label: "Total Readings"
    showBigNumberLabel: true
    style: "K"

tableConfig:
  columnOrder:
    - "airlab_readings_reading_count"
